---
apiVersion: v1
kind: ConfigMap
metadata:
  name: petrosa-realtime-strategies-config
  namespace: petrosa-apps
  labels:
    app: realtime-strategies
    component: trading-signals
data:
  # NATS Configuration
  NATS_CONSUMER_TOPIC: "binance.futures.websocket.data"
  # Changed from "tradeengine.orders" to "signals.trading" to match TradeEngine's subscription
  # This ensures realtime-strategies signals actually reach TradeEngine for processing
  NATS_PUBLISHER_TOPIC: "signals.trading"
  NATS_CONSUMER_NAME: "realtime-strategies-consumer"
  NATS_CONSUMER_GROUP: "realtime-strategies-group"
  
  # Health Check Configuration
  HEALTH_CHECK_PORT: "8080"
  
  # Heartbeat Configuration
  HEARTBEAT_ENABLED: "true"
  HEARTBEAT_INTERVAL_SECONDS: "60"
  HEARTBEAT_INCLUDE_DETAILED_STATS: "true"
  
  # Strategy Configuration
  STRATEGY_ENABLED_ORDERBOOK_SKEW: "true"
  STRATEGY_ENABLED_TRADE_MOMENTUM: "true"
  STRATEGY_ENABLED_TICKER_VELOCITY: "true"
  
  # Market Logic Strategies (from QTZD adaptation)
  STRATEGY_ENABLED_BTC_DOMINANCE: "true"
  STRATEGY_ENABLED_CROSS_EXCHANGE_SPREAD: "false"
  STRATEGY_ENABLED_ONCHAIN_METRICS: "false"
  
  # Order Book Skew Strategy Parameters
  ORDERBOOK_SKEW_TOP_LEVELS: "5"
  ORDERBOOK_SKEW_BUY_THRESHOLD: "1.2"
  ORDERBOOK_SKEW_SELL_THRESHOLD: "0.8"
  ORDERBOOK_SKEW_MIN_SPREAD_PERCENT: "0.1"
  
  # Trade Momentum Strategy Parameters
  TRADE_MOMENTUM_PRICE_WEIGHT: "0.4"
  TRADE_MOMENTUM_QUANTITY_WEIGHT: "0.3"
  TRADE_MOMENTUM_MAKER_WEIGHT: "0.3"
  TRADE_MOMENTUM_BUY_THRESHOLD: "0.7"
  TRADE_MOMENTUM_SELL_THRESHOLD: "-0.7"
  TRADE_MOMENTUM_MIN_QUANTITY: "0.001"
  
  # Ticker Velocity Strategy Parameters
  TICKER_VELOCITY_TIME_WINDOW: "60"
  TICKER_VELOCITY_BUY_THRESHOLD: "0.5"
  TICKER_VELOCITY_SELL_THRESHOLD: "-0.5"
  TICKER_VELOCITY_MIN_PRICE_CHANGE: "0.1"
  
  # Bitcoin Dominance Strategy Parameters (from QTZD adaptation)
  BTC_DOMINANCE_HIGH_THRESHOLD: "70.0"
  BTC_DOMINANCE_LOW_THRESHOLD: "40.0"
  BTC_DOMINANCE_CHANGE_THRESHOLD: "5.0"
  BTC_DOMINANCE_WINDOW_HOURS: "24"
  BTC_DOMINANCE_MIN_SIGNAL_INTERVAL: "14400"
  
  # Cross-Exchange Spread Strategy Parameters (from QTZD adaptation)
  SPREAD_THRESHOLD_PERCENT: "0.5"
  SPREAD_MIN_SIGNAL_INTERVAL: "300"
  SPREAD_MAX_POSITION_SIZE: "500"
  SPREAD_EXCHANGES: "binance,coinbase"
  
  # On-Chain Metrics Strategy Parameters (from QTZD adaptation)
  ONCHAIN_NETWORK_GROWTH_THRESHOLD: "10.0"
  ONCHAIN_VOLUME_THRESHOLD: "15.0"
  ONCHAIN_MIN_SIGNAL_INTERVAL: "86400"
  
  # Trading Configuration
  TRADING_SYMBOLS: "BTCUSDT,ETHUSDT,BNBUSDT"
  TRADING_QUANTITY_PERCENT: "0.1"
  TRADING_MAX_POSITION_SIZE: "1000"
  TRADING_MIN_POSITION_SIZE: "10"
  TRADING_LEVERAGE: "1"
  TRADING_ENABLE_SHORTS: "true"
  
  # Risk Management
  RISK_MAX_DAILY_SIGNALS: "50"
  RISK_MAX_CONCURRENT_POSITIONS: "5"
  RISK_STOP_LOSS_PERCENT: "2.0"
  RISK_TAKE_PROFIT_PERCENT: "4.0"
  RISK_MAX_DRAWDOWN_PERCENT: "10.0"
  
  # Performance Configuration
  BATCH_SIZE: "100"
  BATCH_TIMEOUT: "1.0"
  MAX_MEMORY_MB: "512"
  MAX_CPU_PERCENT: "80"
  MESSAGE_PROCESSING_TIMEOUT: "1.0"
  
  # Circuit Breaker Configuration
  CIRCUIT_BREAKER_FAILURE_THRESHOLD: "5"
  CIRCUIT_BREAKER_RECOVERY_TIMEOUT: "60"
  
  # Message Processing Configuration
  MESSAGE_TTL_SECONDS: "60"
  MESSAGE_MAX_RETRIES: "3"
  MESSAGE_RETRY_DELAY: "1.0"
  
  # Validation Configuration
  VALIDATE_MESSAGES: "true"
  VALIDATE_ORDERS: "true"
  VALIDATE_SYMBOLS: "true"
  
  # Development Configuration
  DEBUG_MODE: "false"
  DRY_RUN_MODE: "false"
  SIMULATION_MODE: "false"
  
  # Strategy Weights
  STRATEGY_WEIGHT_ORDERBOOK_SKEW: "0.4"
  STRATEGY_WEIGHT_TRADE_MOMENTUM: "0.3"
  STRATEGY_WEIGHT_TICKER_VELOCITY: "0.3"
  
  # Signal Confidence Thresholds
  SIGNAL_CONFIDENCE_HIGH: "0.8"
  SIGNAL_CONFIDENCE_MEDIUM: "0.6"
  SIGNAL_CONFIDENCE_LOW: "0.4"
  
  # Order Configuration
  DEFAULT_ORDER_TYPE: "MARKET"
  DEFAULT_TIME_IN_FORCE: "GTC"
  
  # Stream Configuration
  ENABLED_STREAM_TYPES: "depth20,trade,ticker"
